// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqbbddcstjskvkcfcqqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxYmJkZGNzdGpza3ZrY2ZjcXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTAyNDEsImV4cCI6MjA2MTY2NjI0MX0.3jwDzSN0mTaHxHKCyEcbf1Q3wiN16RFmmSpu0JO9YLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);